[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/infrastructure",
    "crates/cli",
    "crates/identifiers",
    "crates/engine",
    "fuzz",
    "crates/engine-client",
    "crates/engine-proto"
]

[workspace.package]
edition = "2024"
rust-version = "1.93.0"
license = "MIT OR Apache-2.0"
authors = ["Leonardo Freitas"]
version = "0.1.0"

[workspace.dependencies]
valqeron-core = { path = "crates/core" }
valqeron-cli = { path = "crates/cli" }
valqeron-infrastructure = { path = "crates/infrastructure" }
valqeron-identifiers = { path = "crates/identifiers" }
valqeron-engine = { path = "crates/engine" }
valqeron-engine-proto = { path = "crates/engine-proto" }
valqeron-engine-client = { path = "crates/engine-client" }
valqeron-fuzz = { path = "fuzz" }

thiserror = "2"
uuid = { version = "1", features = ["v7"] }
chrono = { version = "0.4" }
anyhow = "1.0.104"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"
rusqlite = { version = "0.40.1", features = ["bundled", "hooks"] }
mockall = "0.15.0"
tempfile = "3"
loom = "0.7"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"], default-features = false }
serde_json = "1"
directories = "6"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "time",
    "signal",
    "macros",
    "sync",
    "net",
] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.14.6"
tonic-prost = "0.14.6"
prost-types = "0.14.4"
prost = "0.14.4"
tower = "0.5.3"
hyper-util = "0.1.20"
tonic-prost-build = "0.14.6"
protox = "0.9"
libfuzzer-sys = "0.4.13"
criterion = "0.8.2"
proptest = { version = "1.11.0", default-features = false }
schemars = "1.2.2"
arbitrary = "1.4.2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(loom)"] }
