[package]
name = "valqeron-client"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
valqeron-core = { workspace = true }
valqeron-proto = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
hyper-util = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
