[package]
name = "valqeron-cli"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
valqeron-core = { workspace = true }
valqeron-client = { workspace = true }
valqeron-common = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
directories = { workspace = true }

[[bin]]
name = "valqeron"
path = "src/main.rs"

[lints]
workspace = true
