[package]
name = "valqeron-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
valqeron-core = { workspace = true, features = ["arbitrary"] }

[[bin]]
name = "fuzz_cnpj_equivalence"
path = "fuzz_targets/fuzz_cnpj_equivalence.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_cnpj_ops"
path = "fuzz_targets/fuzz_cnpj_ops.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_cnpj_normalization"
path = "fuzz_targets/fuzz_cnpj_normalization.rs"
test = false
doc = false
bench = false
