[package]
name = "valqeron-core"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"], default-features = false, optional = true }
schemars = { workspace = true, optional = true }
proptest = { workspace = true, default-features = false, optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
valqeron-identifiers = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }
serde_json = { workspace = true }
mockall = { workspace = true }

[features]
serde = ["dep:serde"]
schemars = ["dep:schemars", "serde"]
arbitrary = ["dep:arbitrary"]
proptest = ["dep:proptest"]
codegen = ["dep:serde_json"]


[lib]
name = "valqeron_core"

[lints]
workspace = true

[[bench]]
name = "cnpj_benches"
harness = false