[package]
name = "valqeron-core"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
publish = false

[dependencies]
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
valqeron-identifiers = { workspace = true }
valqeron-common = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }

[lib]
name = "valqeron_core"

[lints]
workspace = true
