[package]
name = "valqeron-engine-client"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
valqeron-engine-proto = { workspace = true }
valqeron-core = { workspace = true }
thiserror = { workspace = true }
tonic = "0.14.6"
tower = "0.5.3"
tokio = "1.53.1"
hyper-util = "0.1.20"
chrono = { workspace = true, features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
uuid = { workspace = true, features = ["serde", "v7"] }
tempfile = "3.27.0"

[lints]
workspace = true
